version: "3.9"

services:
  kasa-exporter:
    image: ghcr.io/ozeliurs/kasa-exporter:latest
    container_name: kasa-exporter
    restart: unless-stopped
    networks:
      - traefik
    env_file:
      - .env
    labels:
      - "traefik.enable=false"

networks:
  traefik:
    external: true
