version: "3.9"

services:
  pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve-exporter
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PVE_VERIFY_SSL=false
    networks:
      - traefik
    labels:
      - traefik.enable=false

networks:
  traefik:
    external: true