version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./conf:/etc/prometheus/conf
      - ./prometheus:/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/conf/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.enable-admin-api
    networks:
      - traefik
    labels:
      - traefik.enable=false

networks:
  traefik:
    external: true