services:
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.1.0
    container_name: nginx-exporter
    restart: unless-stopped
    command: --nginx.scrape-uri=http://192.168.1.71:81/stub_status
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

networks:
  traefik:
    external: true