services:
  headscale-exporter-apoo:
    image: ghcr.io/ozeliurs/headscale-exporter:latest
    container_name: headscale-exporter-apoo
    restart: unless-stopped
    environment:
      - "HEADSCALE_BASE_URL=http://headscale.apoorva64.com:8080/api/v1"
    env_file:
      - .env
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

networks:
  traefik:
    external: true