services:
  postgresql-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    restart: unless-stopped
    environment:
      - DATA_SOURCE_URI=db-kub.oze.li:5432/kub?sslmode=disable
    env_file:
      - .env
    networks:
      - traefik
    labels:
      - "traefik.enable=false"

networks:
  traefik:
    external: true