version: "3.9"

services:
  blackbox:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox
    restart: unless-stopped
    volumes:
      - ./config.yml:/etc/blackbox_exporter/config.yml
    networks:
      - traefik
    cap_add:
      - NET_RAW
    dns:
      - 1.1.1.1
      - 8.8.8.8
    labels:
      - traefik.enable=false

networks:
  traefik:
    external: true